<!DOCTYPE html>
<html lang="en-us">

  <head>
  <meta charset="utf-8">
  <meta name="robots" content="all,follow">
  <meta name="googlebot" content="index,follow,snippet,archive">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Appendix F - Selection procedure</title>
  <meta name="author" content="Mariachiara Fortuna" />
  
  
  
  
  <meta name="keywords" content="R, coding, research, temperature, FGN">
  
  
  <meta name="description" content="">

  <meta name="generator" content="Hugo 0.69.0" />

  
  <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

  
  <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  
  <link href="/css/animate.css" rel="stylesheet">

  
  
    <link href="/css/style.vanlog.css" rel="stylesheet" id="theme-stylesheet">
  

  
  <link href="/css/custom.css" rel="stylesheet">

  
  
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  

  
  <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
  <link rel="apple-touch-icon" href="/img/apple-touch-icon.png" />

  
  <link href="/css/owl.carousel.css" rel="stylesheet">
  <link href="/css/owl.theme.css" rel="stylesheet">

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Vanlog">

  
  
  
  
  
  
  
  <meta property="og:locale" content="en_us">
  <meta property="og:site_name" content="Vanlog">
  <meta property="og:title" content="Appendix F - Selection procedure">
  <meta property="og:type" content="website">
  <meta property="og:url" content="/temperature/appendix-f.utf8/" />
  <meta property="og:description" content="">
  <meta property="og:image" content="/img/temperature/banner_F_selection.png">
  <meta property="og:image:type" content="image/png">
  
  
  
    <meta property="og:image:width" content="369">
    <meta property="og:image:height" content="215">
  
  
  <meta property="og:updated_time" content="2020-04-23T00:00:00Z">
  

  
  <meta name="twitter:card" content="summary">
  
  <meta name="twitter:title" content="Appendix F - Selection procedure">
  
  <meta name="twitter:image" content="/img/temperature/banner_F_selection.png">
  
  <meta name="twitter:description" content="">
  

</head>


  <body>

    <div id="all">

        <header>

          <div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">

    <div class="navbar navbar-default yamm" role="navigation" id="navbar">

        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand home" href="/">
                    <img src="/img/vanlog_retina3.png" alt="Appendix F - Selection procedure logo" class="hidden-xs hidden-sm" >
                    <img src="/img/vanlog_retina3.png" alt="Appendix F - Selection procedure logo" class="visible-xs visible-sm">
                    <span class="sr-only">Appendix F - Selection procedure - go to homepage</span>
                </a>
                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
                      <span class="sr-only">Toggle Navigation</span>
                        <i class="fas fa-align-justify"></i>
                    </button>
                </div>
            </div>
            

            <div class="navbar-collapse collapse" id="navigation">
                <ul class="nav navbar-nav navbar-right">
                  
                  
                  
                  <li class="dropdown">
                    
                    <a href="/">Home</a>
                    
                  </li>
                  
                  
                  <li class="dropdown">
                    
                    <a href="/contact/">Contact</a>
                    
                  </li>
                  
                  
                  <li class="dropdown">
                    
                    <a href="/training/">training</a>
                    
                  </li>
                  
                  
                  <li class="dropdown active">
                    
                    <a href="/temperature/">research</a>
                    
                  </li>
                  
                </ul>
            </div>
            

            <div class="collapse clearfix" id="search">

                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">

                    <button type="submit" class="btn btn-template-main"><i class="fas fa-search"></i></button>

                </span>
                    </div>
                </form>

            </div>
            

        </div>
    </div>
    

</div>






    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>
    


        </header>

        <div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Appendix F - Selection procedure</h1>
            </div>
        </div>
    </div>
</div>


        <div id="content">
            <div class="container">

                <div class="row">

                    

                    <div class="col-md-9" id="blog-post">

                        
                          <p class="text-muted text-uppercase mb-small text-right">
                            By <a href="#">Mariachiara Fortuna</a>
                             | 
                            April 23, 2020
                          </p>
                        

                        <div id="post-content">
                          <p><strong>Affiliations:</strong></p>
<p>John K. Dagsvik, Statistics Norway, Research Department;</p>
<p>Mariachiara Fortuna, freelance statistician, Turin;</p>
<p>Sigmund Hov Moen, Westerdals Oslo School of Arts, Communication and Technology.</p>
<p>\vspace{0.5cm}</p>
<p><strong>Corresponding author:</strong></p>
<p>John K. Dagsvik, E-mail: <a href="mailto:john.dagsvik@ssb.no">john.dagsvik@ssb.no</a></p>
<p>Mariachiara Fortuna, E-mail: <a href="mailto:mariachiara.fortuna@vanlog.it">mariachiara.fortuna@vanlog.it</a> (reference for code and analysis)</p>
<hr>
<h3 id="raw-data-organization">Raw data organization</h3>
<p>The data used in this project were collected by <strong>Sigmund Hov Moen</strong>, and are available in the <strong>Rimfrost system</strong>,  <a href="http://www.rimfrost.no/">www.rimfrost.no</a>.</p>
<p>All the data are available in the tempFgn repository, see the <a href="temperature/temperature-data">temperature data section</a> for more.</p>
<p>They consist of a large amount of monthly and annual temperature time series from all around the world.</p>
<p>The raw data, as organized in the Rimfrost system, are collected in the folder &ldquo;data/raw&rdquo;</p>
<p>The &ldquo;data/raw&rdquo; folder contains 101 subfolders named with the English or the Norwegian name of the countries included in the Rimfrost system.</p>
<p>Each country folder contains the temperature time series for each weather station included in the Rimfrost system.</p>
<h3 id="data-structure">Data structure</h3>
<p>Each time series is collected in a separate txt file, usually named with the Norwegian name of the weather station.</p>
<p>Each file is structured as follow:</p>
<ul>
<li>
<p>Column 1: <strong>Year</strong></p>
</li>
<li>
<p>Columns 2-13: <strong>Monthly temperatures</strong> in that year, from January to December</p>
</li>
<li>
<p>Column 14: <strong>Average annual temperature</strong>, measured as mean of the monthly temperarures for that year</p>
</li>
</ul>
<p>There are no column names, and the missing data are usually recorded with the string <em>99</em> (but several exceptions are present).</p>
<p>As an example, these are the first six rows of the <em>Paris.txt</em> file.</p>
<!-- raw HTML omitted -->
<h3 id="main-features-of-the-raw-data">Main features of the raw data</h3>
<p>In order to select the set of suitable time series and explore their main features, we first provide a preliminary table with useful information (<em>T0_Information</em>). This table contains general information about all the available time series, namely:</p>
<ul>
<li>
<p><strong>Country</strong> and <strong>Station</strong> name for each time series</p>
</li>
<li>
<p>Its <strong>Status</strong>. The Status variable provides the results of some validation checks about the data format. &ldquo;OK&rdquo; means that the time series passed the checks, &ldquo;ERROR&rdquo; means that it did not pass the checks (eg the file has a wrong number of columns)</p>
</li>
<li>
<p><strong>From</strong> and <strong>To</strong> show the first and the last year of the recorded time series</p>
</li>
<li>
<p><strong>Length</strong> shows the length in years of the time series</p>
</li>
<li>
<p><strong>Missing</strong> shows the number of missing annual average temperature. NA means <em>Not Available</em></p>
</li>
</ul>
<p>As an example, consider the first 20 rows of the <em>T0_Information</em> table:</p>
<!-- raw HTML omitted -->
<h3 id="raw-data-basic-exploration">Raw data basic exploration</h3>
<p>The total number of availbale time series is <strong>1260</strong>.</p>
<p>The table below provides a summary of the information given about each recorded variable:</p>
<!-- raw HTML omitted -->
<p>The following graph shows all the available time series, sorted by first recorded year. The green dot represents the first recorded year, while the purple dot represents the last recorded year. The grey segment represents the length of the time series.</p>
<!-- raw HTML omitted -->
<hr>
<h2 id="selection-process">SELECTION PROCESS</h2>
<p>Given the wide variety of properties of the available time series, we decided to apply a multi-step automatic selection procedure to obtain a subset of series with specific characteristics.</p>
<p>In any case, the full set of available time series (1260) is contained in the data/raw folder, and can be analyzed with the provided code.</p>
<h3 id="multi-step-automatic-process">Multi-step automatic process</h3>
<p>Briefly, the multi-step process was designed as follow:</p>
<ol>
<li>
<p><strong>Step 1 - Valid structure</strong>: selection of the time series with valid data structure</p>
</li>
<li>
<p><strong>Step 2 - Length in years</strong>: selection of the time series with more than 105 recorded years</p>
</li>
<li>
<p><strong>Step 3 - Recorded months</strong>: selection of the time series with more than 1280 recorded months (non missing)</p>
</li>
<li>
<p><strong>Step 4 - Missing months</strong>: selection of the time series with less than 80 missing months</p>
</li>
<li>
<p><strong>Step 5 - Length in months</strong>: selection of the time series with full monthly length not inferior to 1290 months</p>
</li>
</ol>
<h3 id="step-1---selection-by-valid-structure">Step 1 - Selection by valid structure</h3>
<p>Using the information table previusly built (<em>T0_Information</em>), we selected all the time series with the variable <em>Status</em> equal to <em>OK</em>.</p>
<p>Here the results of the selection procedure for valid structure (step 1):</p>
<pre><code>##  Cleaning data - Step : 1 
##  ************************************ 
##  1035 accepted time series over 1260 
##  Current step acceptance rate : 82.14 % 
##  Loss from step 1: 17.86 %
</code></pre><h3 id="step-2---selection-by-length-years">Step 2 - Selection by length (years)</h3>
<p>The second step of our selection procedure was to identify all the time series that had more than 106 recorded years.</p>
<p>The results of the second step of the selection procedure follows here:</p>
<pre><code>##  Cleaning data - Step : 2 
##  ************************************ 
##  376 accepted time series over 1035 
##  Current step acceptance rate : 36.33 % 
##  Loss from step 1: 70.16 %
</code></pre><p>At this point, our subset consists of 376 weather stations.</p>
<h3 id="information-table-2---monthly-information">Information table 2 - Monthly information</h3>
<p>In order to apply step 3-5 of the selection procedure, we need to gather information about the data at a monthly level.</p>
<p>We then built a second information table, with the following fields:</p>
<ul>
<li>
<p><strong>Country</strong> and <strong>Station</strong> name for each time series</p>
</li>
<li>
<p><strong>First_Year</strong> and <strong>First_Year</strong>, first and the last year of the recorded time series</p>
</li>
<li>
<p><strong>Years</strong>, length in years of the time series</p>
</li>
<li>
<p><strong>Months</strong>, number of available months (non missing)</p>
</li>
<li>
<p><strong>Full_Length</strong>, number of months between the first recorded month and the last one.</p>
</li>
<li>
<p><strong>Missing_M</strong>, number of missing months</p>
</li>
</ul>
<p>As an example, consider the the first 10 rows of the <em>T02_Information2</em> table:</p>
<!-- raw HTML omitted -->
<h3 id="step-3---selection-by-available-months">Step 3 - Selection by available months</h3>
<p>We can now refine the selection procedure checking that the number of <em>non missing months</em> is superior to <em>1260</em>.</p>
<p>Here the results of this selection step:</p>
<pre><code>##  Cleaning data - Step : 3 
##  ************************************ 
##  329 accepted time series over 376 
##  Current step acceptance rate : 87.5 % 
##  Loss from step 1: 73.89 %
</code></pre><h3 id="step-4---selection-by-missing-months">Step 4 - Selection by missing months</h3>
<p>We can now exclude all the time series with number of <em>missing months</em> above <em>80</em>.</p>
<p>Recall that the previous step was about non missing months: in this step we are avoiding time series that (although long), contain so many &ldquo;holes&rdquo; that they might compromise the data quality.</p>
<p>Here the results of this selection step:</p>
<pre><code>##  Cleaning data - Step : 3 
##  ************************************ 
##  278 accepted time series over 329 
##  Current step acceptance rate : 84.5 % 
##  Loss from step 1: 77.94 %
</code></pre><h3 id="step-5---length-in-months">Step 5 - Length in months</h3>
<p>The last step of the selection procedure is to check if the total length of the time series (from the first recorded month to the last one, missing included) is not inferior to 1290.</p>
<p>Above the results:</p>
<pre><code>##  Cleaning data - Step : 5 
##  ************************************ 
##  277 accepted time series over 278 
##  Current step acceptance rate : 99.64 % 
##  Loss from step 1: 78.02 %
</code></pre><p>At this point we have a subset of 277 waether stations, characterized by a valid data structure and a length and presence of missing observation below specific thresholds.</p>
<h2 id="final-selection">Final selection</h2>
<p>In order to select the final set of weather stations we proceded by manual inspection of all the time series.</p>
<p>We excluded all the time series with substantial quality problems, such as those with extreme outliers and several consecutive missing over time intervals.</p>
<p>In the final selection we tried as much as possible to select weather stations that were distributed across most parts of the world.</p>
<!-- raw HTML omitted -->
<!-- raw HTML omitted -->
<h3 id="final-data">Final data</h3>
<p>Summary statistics of the selected of 96 time series is shown in <a href="/temperature/appendix-b">Appendix B</a>, table B1.</p>
<p>There are two time series that did not pass the tests but we still included them in our analysis. One is from Ivittuut, Greenland, and the second one is from Uppsala, Sweden. The reason is that Greenland is of particular interest in the climate debate, and the temperature series from Uppsala is the longest time series ever recorded.</p>
<p>All the selected time series are available in the data/final folder. All the names (country and stations) have been translated to English.</p>
<p>We have highlighted results from 9 weather stations because they are well known cities with good quality of the temperature data.</p>

                        </div>
                        
                        

                    </div>
                    

                    

                    

                    <div class="col-md-3">

                        

                        

<div class="panel panel-default sidebar-menu">

    <div class="panel-heading">
      <h3 class="panel-title">Search</h3>
    </div>

    <div class="panel-body">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" role="search">
            <div class="input-group">
                <input type="search" name="q" class="form-control" placeholder="Search">
                <input type="hidden" name="sitesearch" value="/">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-template-main"><i class="fas fa-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>







<div class="panel panel-default sidebar-menu">

    <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
    </div>

    <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
            
            
            <li>
                <a href="/categories/research">research (11)</a>
            </li>
            
        </ul>
    </div>

</div>








<div class="panel sidebar-menu">

    <div class="panel-heading">
        <h3 class="panel-title">Tags</h3>
    </div>

    <div class="panel-body">
        <ul class="tag-cloud">
            
            
            <li>
                <a href="/tags/fgn"><i class="fas fa-tags"></i> fgn</a>
            </li>
            
            <li>
                <a href="/tags/open-data"><i class="fas fa-tags"></i> open-data</a>
            </li>
            
            <li>
                <a href="/tags/plot"><i class="fas fa-tags"></i> plot</a>
            </li>
            
            <li>
                <a href="/tags/r"><i class="fas fa-tags"></i> r</a>
            </li>
            
            <li>
                <a href="/tags/r-package"><i class="fas fa-tags"></i> r-package</a>
            </li>
            
            <li>
                <a href="/tags/regression"><i class="fas fa-tags"></i> regression</a>
            </li>
            
            <li>
                <a href="/tags/research"><i class="fas fa-tags"></i> research</a>
            </li>
            
            <li>
                <a href="/tags/temperature"><i class="fas fa-tags"></i> temperature</a>
            </li>
            
        </ul>
    </div>

</div>






                        

                    </div>
                    

                    

                </div>
                

            </div>
            
        </div>
        

        <footer id="footer">
    <div class="container">

        
        <div class="col-md-4 col-sm-6">
            <h4>About us</h4>

            Vanlog is a group of data scientists born around a common goal: bringing the power of data everywhere. We believe in open source solutions and we specializes in R, the programming language for statistical solutions

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        
        

        <div class="col-md-4 col-sm-6">

            

        </div>
        

        
        <div class="col-md-4 col-sm-6">

          <h4>Contact</h4>

            <p class="text-uppercase"><strong>Vanlog</strong>
    <br> Torino 
    <br> Milano  
      </p>
      

            <a href="/contact" class="btn btn-small btn-template-main">Go to contact page</a>

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        
        

    </div>
    
</footer>







<div id="copyright">
    <div class="container">
        <div class="col-md-12">
            
            <p class="pull-left">Copyright (c) 2020, Vanlog; all rights reserved.</p>
            
            <p class="pull-right">
              Template by <a href="https://bootstrapious.com/p/universal-business-e-commerce-template">Bootstrapious</a>.
              

              Ported to Hugo by <a href="https://github.com/devcows/hugo-universal-theme">DevCows</a>.
            </p>
        </div>
    </div>
</div>





    </div>
    

    
<script src="//code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0/jquery.counterup.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-parallax/1.1.3/jquery-parallax.js"></script>

<script src="//maps.googleapis.com/maps/api/js?v=3.exp"></script>

<script src="/js/hpneo.gmaps.js"></script>
<script src="/js/gmaps.init.js"></script>
<script src="/js/front.js"></script>


<script src="/js/owl.carousel.min.js"></script>



  </body>
</html>
