---
title: Temperature Data
author: ''
date: '2020-04-23'
slug: temperature-data
type: norender
categories: []
order: 2
tags: []
---


Since the goal of this work was to study the temperatures fluctuations
over time, we needed long temperatures time series, possibly for more than
one weather station. 

We found a great solution in the data collected by Sigmund H. Moen, co-author of this paper and creator of the web page www.rimfrost.no, where most of the record are freely available. The data consist in a big amount of temperatures time series, certified by NASA, for more than 100 countries, giving a total of 1258 weather stations; the time series are available as yearly, monthly and even three-times-a-day observations, and the length of the time series may vary greatly from station to station: while some of them are less than ten years long, the longer time series, from the city of Upssala in Sweden, is 290 years long, with monthly data from 1722 to 2012, at the time were the data were collected.

The time series included in the Rimfrost system were much more than we
needed. The aim of our study was to establish if a Gaussian and self-similar model might be applied to the temperatures fluctuations. If one proof could
be not enough, a great fitting in a dozen of weather station would have been
more than sufficient. Anyway, since we found ourself with this treasure, we
decided to repeat the analyses for all the time series which met selection
criteria based on length and cleanness of the records, as described in Appendix F. 

Furhtermore, in order to test the same hypothesis on a two millenia recostructed time serie, we recurred to the Moberg recostructed data [cit], available here xxx.

Following the link below you can access and download all the data that were, in various measures, used to produce this paper. 

The original data, as collected from the Rimfrost system, are available in the /raw folder. It contains 1260 files, one for each collected time series.

The /final folder contains a subset of 96 of the 1260 files, selected because they meet criteria of lenght and data quality as described in Appendix F. 

The /moberg folder contains the moberg data.


# Temperature time series data structure

Each time series is collected in a separate txt file, usually named with the Norwegian name of the weather station.

Each file is structured as follow:

• Column 1: Year
• Columns 2-13: Monthly temperatures in that year, from January to December
• Column 14: Average annual temperature, measured as mean of the monthly temperarures for that year

There are no column names, and the missing data are usually recorded with the string 99 (but several exceptions are present).

As an example, these are the first six rows of the Paris.txt file.

<embed src="/img/temperature/Paris_head" width="70%" height="775" />


## /raw folder

The /raw folder contains 101 subfolders named with the English or the Norwegian name of the countries included in the Rimfrost system.
Each country folder contains the temperature time series for each weather station included in the Rimfrost system.


## /final folder

As stated before, through the selection procedure described in Appendix F we selected a subset of 96 time series. These time series satisfy quality criteria as adequate length in years, lack of anomalies, reduced precence of missing records.    
All the selected time series are available in the /final folder. All the names (country and stations) have been translated to English.


# Moberg data

Temperature reconstructed time series from Moberg et al. are available in the /moberg folder 
